---
title: "Riddler Challenge: Expected Draft Pick"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
library(plotly)

# function to calculate expected draft position
draft_pick_sim <- function(n_groups = 2, n_teams = 30, n_sims = 100){
  old <- 1:n_teams

  sims <- replicate(n_sims, sample(1:n_groups, n_teams, replace = T)) %>%
    tbl_df %>%
    bind_cols(data_frame(old)) %>%
    gather(sim, outcome, -old) %>%
    group_by(sim) %>%
    arrange(sim, outcome, old) %>%
    mutate(new = row_number())
  
  return(sims)
}
```

Inputs {.sidebar}
-------------------------------------

```{r}
numericInput("n_teams",
             "Number of teams:",
             min = 1,
             max = 99,
             value = 30)

renderUI({
  numericInput("n_groups",
               "Number of groups to split into:",
               min = 2,
               max = input$n_teams,
               value = 2)
})
```

Column
-----------------------------------------------------------------------

```{r}
tn <- reactive(draft_pick_sim(n_groups = input$n_groups,
                              n_teams = input$n_teams,
                              n_sims = 10000))

output$plot <- renderPlotly({
  plot_build <- tn() %>%
    ungroup %>%
    count(old, new) %>%
    ungroup %>%
    complete(old, new, fill = list(n = 0)) %>%
    group_by(old) %>%
    mutate(pct = n / sum(n)) %>%
    rename(Original = old,
           Expected = new,
           Percent = pct) %>%
    ggplot(aes(Original, Expected, fill = Percent, text = paste0("Percent: ", Percent * 100, "%"))) +
    geom_raster() +
    scale_fill_continuous(low = "white", high = "blue",
                          labels = scales::percent) +
    labs(title = "Expected Draft Pick",
         x = "Original Draft Position",
         y = "Expected Draft Position",
         fill = NULL) +
    theme_bw(base_size = 18) +
    theme(legend.position = "bottom")
  ggplotly(plot_build,
           tooltip = c("x", "y", "text"))
})

plotlyOutput("plot", width = "100%", height = "100%")
```
